### PR TITLE
[WIP] visibility of bluetooth adapter

### PR DESCRIPTION
**Pull request by miniskipper**
visibility of adapter only 60s/while manager is open
make it visible when clicking header icon (manager)
menu item to make it visible (tray)
reset discoverable/timeout after suspend

see issue #67

### CODE REVIEW

**Review by leigh123linux — CHANGES_REQUESTED** [review]
60 seconds is far too low, please increase to 300

**Comment by miniskipper** [comment]
> 60 seconds is far too low, please increase to 300

done

**Comment by mtwebster** [comment]
See my comments on the issue you linked. I'm fine with adding a limited-duration trigger from the status icon, but I don't really agree with making discoverability limited within the main blueberry window.

This pr currently doesn't actually turn off discoverability - it still remains active as long as the window is. Clicking the icon in the corner isn't really discoverable (no pun intended) feature - there would need to be a more obvious way, as well as some indicator to show whether it's currently active or not. But as I said, I'm not sure this is a positive change or not.

**Comment by clefebvre** [comment]
Too old, closing the PR.

**Pull request closed without merging**
