### PR TITLE
Don't use /usr/bin/env to call python3

### PR DESCRIPTION
**Pull request by okaestne**
This avoids problems like issue #96

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This does not solve the issue for eco systems like nix which do not have ``/usr/bin/python3``. I am for a revert of this and a proper fix.

**Comment by okaestne** [comment]
Using `/usr/bin/env` would be against the [Debian Python Policy](https://debian-python.readthedocs.io/en/latest/debian-policy.html#interpreter-location).

Also most other Mint tools use `/usr/bin/python3`, do they cause issues as well?

**Comment by leigh123linux** [comment]
@SuperSandro2000  How did nix fix this?

https://github.com/linuxmint/cinnamon/commit/ffbd4a767e225367f8b34a568172c95d7d908ff6

Is patchShebangs a nix script to fix shebangs?

https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/cinnamon/cinnamon-common/default.nix#L132

**Comment by SuperSandro2000** [comment]
> Using `/usr/bin/env` would be against the [Debian Python Policy](https://debian-python.readthedocs.io/en/latest/debian-policy.html#interpreter-location).

We a conflict of interest here.

> Also most other Mint tools use /usr/bin/python3, do they cause issues as well?

Without

> Is patchShebangs a nix script to fix shebangs?

Yes. We can always fix it but it is some extra step which could be avoided.

**Pull request merged**
